### ISSUE TITLE
Test all M6502 instruction functions

### ISSUE THREAD

**Issue by dannyhvc** [dannyhvc/nes_emulator_rust#12]
### Title: 
Test All CPU Instruction Functions

### Description:
Several CPU instruction functions that need to be thoroughly tested.

For each function, the tests should include:

- A variety of input scenarios to cover all possible edge cases.
- Expected outputs for each input scenario.
- Any side effects the function might have.

This will greatly improve the reliability of our codebase, and ensure that our CPU instruction functions are working as expected.

### Tasks:
- [ ] Identify all CPU instruction functions that need testing.
- [ ] Write comprehensive tests for each identified function.
- [ ] Run the tests and fix any issues that are discovered.
